import { colors, semanticTokens } from './src/skillmaster/colors.js';
import plugin from 'tailwindcss/plugin';

/**
 * Tailwind Plugin — Design Token CSS Variable Generator
 *
 * Reads `semanticTokens` from colors.js and generates :root (light) and
 * .dark CSS custom properties automatically. This ensures colors.js is
 * the single source of truth for every color in the app.
 */
const designTokenPlugin = plugin(function ({ addBase }) {
    const rootVars = {};
    for (const [key, value] of Object.entries(semanticTokens.light)) {
        rootVars[key] = value;
    }

    const darkVars = {};
    for (const [key, value] of Object.entries(semanticTokens.dark)) {
        darkVars[key] = value;
    }

    addBase({
        ':root': rootVars,
        '.dark': darkVars,
    });
});

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: colors.primary,
                secondary: colors.secondary,
                gray: colors.grays,

                // Semantic Tokens (reference CSS variables generated by plugin)
                surface: {
                    app: 'var(--bg-app)',
                    base: 'var(--bg-surface)',
                    2: 'var(--bg-surface-2)',
                    elev: 'var(--bg-elev-1)',
                },
                content: {
                    primary: 'var(--text-primary)',
                    muted: 'var(--text-muted)',
                    subtle: 'var(--text-subtle)',
                },
                stroke: {
                    base: 'var(--border-base)',
                    highlight: 'var(--border-highlight)',
                }
            },
            borderRadius: {
                'card': '20px',
                'phoneMock': '24px',
            },
            fontFamily: {
                sans: ['Manrope', 'sans-serif'],
                heading: ['Sora', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'hero-base': ['32px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
                'hero-sm': ['40px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
                'hero-md': ['48px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
                'hero-lg': ['56px', { lineHeight: '1.05', fontWeight: '800', letterSpacing: '-0.02em' }],
                'section-label': ['12px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0.08em' }],
                'card-title': ['13px', { lineHeight: '1.3', fontWeight: '700' }],
                'card-body': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
                'footer-sm': ['11px', { lineHeight: '1.4', fontWeight: '400' }],
            },
            boxShadow: {
                'sm': 'var(--shadow-sm)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
                'glass': 'var(--glass-shadow)',
                'hero-media': `0 20px 60px -5px ${colors.accents.shadowSoft}, 0 10px 30px -5px ${colors.accents.shadowCrimson}`,
                'card-soft': 'var(--shadow-sm)',
                'card-hover': 'var(--shadow-md)',
                'btn-primary': `0 4px 14px 0 ${colors.primary[600]}80`,
                'btn-primary-hover': `0 6px 20px ${colors.primary[600]}66`,
                'btn-secondary': `0 4px 14px 0 ${colors.secondary[500]}66`,
                'glow-primary': `0 0 20px ${colors.primary[600]}99`,
                'glow-secondary': `0 0 20px ${colors.secondary[500]}80`,
            },
            backgroundImage: {
                'primary-gradient': `linear-gradient(135deg, ${colors.primary[500]} 0%, ${colors.primary[600]} 100%)`,
                'primary-gradient-hover': `linear-gradient(135deg, ${colors.primary[400]} 0%, ${colors.primary[500]} 100%)`,
                'secondary-gradient': `linear-gradient(135deg, ${colors.secondary[500]} 0%, ${colors.secondary[600]} 100%)`,
                'secondary-gradient-hover': `linear-gradient(135deg, ${colors.secondary[400]} 0%, ${colors.secondary[500]} 100%)`,
                'glass-gradient': `linear-gradient(135deg, ${colors.accents.cardBorderLight} 0%, rgba(255,255,255,0.05) 100%)`,

                'app-gradient-light': `radial-gradient(circle at 50% 0%, ${colors.primary[500]}08 0%, transparent 50%), radial-gradient(circle at 100% 0%, ${colors.secondary[500]}0D 0%, transparent 40%)`,
                'app-gradient-dark': `radial-gradient(circle at 50% 0%, ${colors.primary[500]}14 0%, transparent 50%), radial-gradient(circle at 100% 0%, ${colors.secondary[500]}0F 0%, transparent 40%)`,

                'accent-wash': 'var(--accent-wash)',
            },
            animation: {
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'float': 'float 6s ease-in-out infinite',
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-10px)' },
                }
            }
        },
    },
    plugins: [designTokenPlugin],
}
