import { colors } from './src/skillmaster/colors.js';

/**
 * Tailwind Configuration
 *
 * Color palette values come from colors.js (single source of truth).
 * Semantic CSS variables (:root / .dark) are generated by
 * scripts/generate-tokens.js and imported into index.css.
 */

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                primary: {
                    DEFAULT: colors.primary.cardinal,
                    hover: colors.primary.cardinalHover,
                    ...colors.primary,
                },
                secondary: {
                    DEFAULT: colors.primary.gold,
                    ...colors.primary, // map generic secondary to gold/primary for safety or strict new tokens
                },
                neutral: colors.neutral,

                // Semantic Tokens
                surface: {
                    app: 'var(--bg-app)',
                    base: 'var(--bg-surface)',
                    2: 'var(--bg-surface-2)',
                    elev: 'var(--bg-elev-1)',
                },
                content: {
                    primary: 'var(--text-primary)',
                    muted: 'var(--text-muted)',
                    subtle: 'var(--text-subtle)',
                },
                stroke: {
                    base: 'var(--border-base)',
                    highlight: 'var(--border-highlight)',
                }
            },
            borderRadius: {
                'card': '0px', // Brand identity says 0px radius or clean cards? "clean cards"
                // Checking design-tokens.json: "border_radius": "0px"
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                heading: ['"Libre Baskerville"', 'Georgia', 'serif'],
            },
            backgroundImage: {
                'primary-gradient': `linear-gradient(to right, ${colors.primary.cardinal}, ${colors.primary.gold})`,
            },
            boxShadow: {
                'sm': 'var(--shadow-sm)',
                'md': 'var(--shadow-md)',
                'lg': 'var(--shadow-lg)',
            },
        },
    },
    plugins: [],
}
